services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017/argentbank
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_URL=http://server:3001
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./client:/app
      - next_data:/app/.next
      - /app/node_modules
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  next_data:
